blank_issues_enabled: false
contact_links:
  - name: "ğŸš€ Feature Request"
    url: https://discuss.flarum.org/t/proposals
    about: |
      Thanks for taking the time to fill out this feature request!
      We primarily use GitHub as a bug tracker and issue tracker for items we are sure to tackle in the near future.
      For feature requests, ideas and feedback please post in the Flarum Community.
      Feature requests are added to GitHub only when they have been accepted by the development team and implementation details have been laid out.
  - name: "ğŸ™‹â€ Support Question"
    url: https://discuss.flarum.org/t/support
    about: |
      We primarily use GitHub as a bug tracker and issue tracker for items we are sure to tackle in the near future; for usage and support questions, please check out these resources below. Thanks!

      * Flarum Community: https://discuss.flarum.org/
      * Discord Chat: https://flarum.org/discord/
      * Twitter: https://twitter.com/Flarum
