language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  - composer install
  - mysql -e 'CREATE DATABASE flarum_test;'

before_script:
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer test:setup

script:
  - composer test

jobs:
  include:
    - php: 7.1
      env: DB=mysql

    - php: 7.2
      env: DB=mysql

    - php: 7.3
      env: DB=mysql

    - php: 7.1
      addons:
        mariadb: '10.2'
      env: DB=mariadb

    - php: 7.2
      addons:
        mariadb: '10.2'
      env: DB=mariadb

    - php: 7.3
      addons:
        mariadb: '10.2'
      env: DB=mariadb

    - php: 7.2
      env: DB=mysql PREFIX=forum_

    - stage: build
      language: generic
      if: branch = master AND type = push
      install: skip
      script: bash .travis/build.sh
        -k $encrypted_678139e2bc67_key
        -i $encrypted_678139e2bc67_iv
      after_success: skip
