name: JavaScript

on:
  push:
    branches:
      - master

jobs:
  build:
    name: JS / Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('js/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Our action will install npm, cd into `./js`, run `npm run build` and
      # `npm run build-typings`, then commit and upload any changes
      - name: Build production JS
        uses: flarum/action-build@2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: build
          package_manager: npm
          typings_script: build-typings
