name: Bundle size checker

on:
  workflow_dispatch:

  push:
    paths:
      - "js/**"
  pull_request:
    paths:
      - "js/**"

jobs:
  bundlewatch:
    runs-on: ubuntu-latest

    name: Bundlewatch

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Use npm v7
        run: sudo npm install -g npm@7.x.x

      - name: Install JS dependencies
        run: npm ci
        working-directory: ./js

      - name: Build production assets
        run: npm run build
        working-directory: ./js

      - name: Check bundle size change
        run: node_modules/.bin/bundlewatch --config .bundlewatch.config.json
        working-directory: ./js
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
